
[git_status]
up_to_date = "ï® "
stashed = "ï’‡ "
ahead = "â‡¡${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind = "â‡£${count} "
staged = "î«œ "
untracked = "ó±™ "
format = "([$all_status$ahead_behind]($style) )"

[aws]
style = 'bold blue'
symbol = 'ğŸ…° '

[aws.region_aliases]
eu-west-1 = 'eu'
